# Generated by Django 2.2.4 on 2019-08-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_date',
        ),
    ]
