# Generated by Django 2.2.4 on 2019-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='step_10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='step_9',
            field=models.TextField(blank=True),
        ),
    ]
