# Generated by Django 2.2.4 on 2019-08-24 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190824_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
