# Generated by Django 2.2.4 on 2019-08-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default='none', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
