# Generated by Django 2.2.4 on 2019-08-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='家常菜', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='ingredient',
            field=models.TextField(default='lalalalalala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='step_1',
            field=models.TextField(default='把食材放进锅里'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='step_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_10_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_1_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_2_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_3_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_4_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_5_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_6_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_7_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_8_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='step_9_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
