# Generated by Django 2.2.4 on 2019-08-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_likedblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedblog',
            name='like_date',
        ),
    ]
